### ISSUE TITLE
scanner integrations

### ISSUE THREAD

**Issue by theretr0o0** [Mixeway/MixewayHub#24]
Hello and thanks for publishing Mixeway. In my own scenario, I want to connect the mixeway with 5 scanners
01. Nessus-8.12.1
02. Burpsuite pro v2020.9.2
03. OWASP ZAP 2.9.0
04. OpenVAS/GVM 20
05. Acunetix v13
The first 3 scanners connected without any problems and the message "Test Passed" is displayed when retesting but have not yet been identified as active scanners, which is my first problem.
And because OpenVAS 9 and 10 are obsolete, I used gvm 20, but I could not find enough information to connect it to the mixeway.
In the case of Acunetix, I did exactly what was said in the document, but it does not connect.

**Comment by siewer** [comment]
Hello!
1. Nessus in version 8 could be a problem. All version above 6 has removed API which allows to remotely run the scan. If You want full integration with nessus - configure scan, start the scan and load vulnerabilities from mixeway max version is 6
2. In Scope of Burpsuite only Burpsuite Enterprise Edition is supported. Burp EE provide API which mixeway use in order to configure scan run it and load results. Burp Pro does not have that option (or does it?)
3. OWASP ZAP is not yet supported
4. OpenVAS/GVM - we have only tested GVM 9, 10 and 11. Nativly GVM does not come with REST API so we have prepared one which is mandatory to be used - https://github.com/Mixeway/MixewayOpenVASRestAPI I am already preparing complex guide how to use it. I have no idea if MixewayOpenVASRestAPI will work on fvm 20
5. Acunetix v13 is tested and proved to be working can You provide some logs to investigate the problem?

In every next releases we are trying to cover more integrations. But I believe we have to improve docs to cover more stuff.

**Comment by theretr0o0** [comment]
Thanks for the quick reply
Burp Pro also supports rest api, but I also tried the enterprise version, but it is not recognized as an active scanner as before.
I tested MixewayOpenVASRestAPI for gvm 20 and it does not work.
And here are the logs related to Acunetix v13:


[32mMixerBackend          |[0m 2020-11-14 08:03:46.875  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.875  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.877  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.877  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.879  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.879  INFO 1 --- [nio-8443-exec-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.886 ERROR 1 --- [nio-8443-exec-1] i.m.r.a.service.AdminScannerRestService  : Cannot add scanner http://192.168.8.171:3443 - I/O error on GET request for "http://192.168.8.171:3443/api/v1/targets": Connection reset; nested exception is java.net.SocketException: Connection reset
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:08:03:46 +0000] "PUT /v2/api/admin/scanner/add HTTP/1.1" 412 78 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[32mMixerBackend          |[0m 2020-11-14 08:03:46.949  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.949  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.952  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.952  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.957  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.8.171:3443: Connection reset
[32mMixerBackend          |[0m 2020-11-14 08:03:46.958  INFO 1 --- [nio-8443-exec-2] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://192.168.8.171:3443
[32mMixerBackend          |[0m 2020-11-14 08:03:46.961 ERROR 1 --- [nio-8443-exec-2] i.m.r.a.service.AdminScannerRestService  : Cannot add scanner http://192.168.8.171:3443 - I/O error on GET request for "http://192.168.8.171:3443/api/v1/targets": Connection reset; nested exception is java.net.SocketException: Connection reset

Nessus Logs:


[33mMixerBackend          |[0m 2020-11-14 09:31:46.422 ERROR 1 --- [nio-8443-exec-9] i.m.i.i.p.n.apiclient.NessusApiClient    : Error occured during nessus initialize - http://192.168.8.171:8834/ - 400 BAD_REQUEST 400 Bad Request: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">


[33mMixerBackend          |[0m <html><head>


[33mMixerBackend          |[0m <title>400 Bad Request</title></head><body><h1>Bad Request</h1><p>Your browser sent a request that this server could not understand.<br>Reason: You're speaking plain HTTP to an SSL-enabled server port.<br>Instead, please use the HTTPS scheme to access this URL.<br></p></body></html>]
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:46 +0000] "PUT /v2/api/admin/scanner/97/test HTTP/1.1" 200 74 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:46 +0000] "GET /v2/api/admin/scanners HTTP/1.1" 200 465 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"


I even had a problem with the burpEE version:

[33mMixerBackend          |[0m 2020-11-14 09:31:52.849 ERROR 1 --- [io-8443-exec-10] i.m.i.w.p.b.apiclient.BurpEEApiClient    : Cannot initialize scanner http://192.168.8.161:8070/api/tvM8hn0pGiDEEGDVF4LfrdVHdvNWGJVS - 400 BAD_REQUEST
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:52 +0000] "PUT /v2/api/admin/scanner/109/test HTTP/1.1" 200 74 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:52 +0000] "GET /v2/api/admin/scanners HTTP/1.1" 200 465 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

and OWASP Logs:


[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:59 +0000] "PUT /v2/api/admin/scanner/63/test HTTP/1.1" 200 74 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[35mMixerFrontend         |[0m 192.168.8.1 - - [14/Nov/2020:09:31:59 +0000] "GET /v2/api/admin/scanners HTTP/1.1" 200 465 "https://192.168.8.169/pages/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by siewer** [comment]
Apologies for late response.

I have done some checks
1. I have tested acunetix (Version: 13.0.201112128) which works ok. Are You sure You are not using HTTPS certificate? From logs looks like there API endpoint You are using is http. Exception which is thwon is related with network issues
2. Nessus this one I am unable to test last version verified is version Nessus v6
3. GVM20 I have done some research (I have not installed it yet) but from what I see it should work, however configuration could be painfull - in case of a problems pls issue separate ticket so I will walk You through.
4. I have no access to Burp pro but from what i see pro and ee versions vary in terms of API. In order to initialize scanner mixeway is using "/api-internal/scan-configurations" endpoint of Burp EE REST API to load scan configurations. I am not able to find this endpoint in burp pro docs https://portswigger.net/blog/burps-new-rest-api

**Comment by siewer** [comment]
Closed due to inactivity
